#!/usr/local/bin/perl

## This is an example of how to set the child process into a view
## and control it. Note that although this will work on both UNIX
## and Windows, it will give errors on Windows because that's
## what the CC developers chose to do for some reason.

use ClearCase::Argv qw(ccsystem ccqx);

## Setting a view requires that you be in IPC::ClearTool mode.
ClearCase::Argv->ipc_cleartool;

# Print out each command before executing it (like sh -x).
ClearCase::Argv->dbglevel(1);

my $ct = ClearCase::Argv->new;
$ct->autochomp;

# Get a list of the local views.
my @views = $ct->cmd('lsview -s')->qx;

print "\n*Show that we can set the coprocess into a view and keep it there.\n";
$ct->cmd('pwv -s')->system;
$ct->cmd('setview', [], $views[0])->system;
$ct->cmd('pwv -s')->system;
# ... from here you could cd into a vob and do whatever you want.

print "\n*Similar to above but using the functional interface ...\n";
ClearCase::Argv->dbglevel(0);
for my $view (reverse @views) {
    ccsystem('setview', $view);
    my $cwv = ccqx('pwv -s');
    chomp $cwv;
    print "Setting cleartool process into view '$cwv'\n";
}
